-- Users
INSERT INTO users (name, email) VALUES ('User 1', 'user1@example.com');
INSERT INTO users (name, email) VALUES ('User 2', 'user2@example.com');
INSERT INTO users (name, email) VALUES ('User 3', 'user3@example.com');
INSERT INTO users (name, email) VALUES ('User 4', 'user4@example.com');
INSERT INTO users (name, email) VALUES ('User 5', 'user5@example.com');
INSERT INTO users (name, email) VALUES ('User 6', 'user6@example.com');
INSERT INTO users (name, email) VALUES ('User 7', 'user7@example.com');
INSERT INTO users (name, email) VALUES ('User 8', 'user8@example.com');
INSERT INTO users (name, email) VALUES ('User 9', 'user9@example.com');
INSERT INTO users (name, email) VALUES ('User 10', 'user10@example.com');
INSERT INTO users (name, email) VALUES ('User 11', 'user11@example.com');
INSERT INTO users (name, email) VALUES ('User 12', 'user12@example.com');
INSERT INTO users (name, email) VALUES ('User 13', 'user13@example.com');
INSERT INTO users (name, email) VALUES ('User 14', 'user14@example.com');
INSERT INTO users (name, email) VALUES ('User 15', 'user15@example.com');
INSERT INTO users (name, email) VALUES ('User 16', 'user16@example.com');
INSERT INTO users (name, email) VALUES ('User 17', 'user17@example.com');
INSERT INTO users (name, email) VALUES ('User 18', 'user18@example.com');
INSERT INTO users (name, email) VALUES ('User 19', 'user19@example.com');
INSERT INTO users (name, email) VALUES ('User 20', 'user20@example.com');
INSERT INTO users (name, email) VALUES ('User 21', 'user21@example.com');
INSERT INTO users (name, email) VALUES ('User 22', 'user22@example.com');
INSERT INTO users (name, email) VALUES ('User 23', 'user23@example.com');
INSERT INTO users (name, email) VALUES ('User 24', 'user24@example.com');
INSERT INTO users (name, email) VALUES ('User 25', 'user25@example.com');
INSERT INTO users (name, email) VALUES ('User 26', 'user26@example.com');
INSERT INTO users (name, email) VALUES ('User 27', 'user27@example.com');
INSERT INTO users (name, email) VALUES ('User 28', 'user28@example.com');
INSERT INTO users (name, email) VALUES ('User 29', 'user29@example.com');
INSERT INTO users (name, email) VALUES ('User 30', 'user30@example.com');
INSERT INTO users (name, email) VALUES ('User 31', 'user31@example.com');
INSERT INTO users (name, email) VALUES ('User 32', 'user32@example.com');
INSERT INTO users (name, email) VALUES ('User 33', 'user33@example.com');
INSERT INTO users (name, email) VALUES ('User 34', 'user34@example.com');
INSERT INTO users (name, email) VALUES ('User 35', 'user35@example.com');
INSERT INTO users (name, email) VALUES ('User 36', 'user36@example.com');
INSERT INTO users (name, email) VALUES ('User 37', 'user37@example.com');
INSERT INTO users (name, email) VALUES ('User 38', 'user38@example.com');
INSERT INTO users (name, email) VALUES ('User 39', 'user39@example.com');
INSERT INTO users (name, email) VALUES ('User 40', 'user40@example.com');

-- Venues
INSERT INTO venues (name, city, capacity) VALUES ('Venue 1', 'Porto', 1010);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 2', 'Lisboa', 1020);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 3', 'Braga', 1030);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 4', 'Coimbra', 1040);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 5', 'Faro', 1050);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 6', 'Aveiro', 1060);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 7', 'Guimarães', 1070);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 8', 'Viseu', 1080);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 9', 'Setúbal', 1090);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 10', 'Évora', 1100);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 11', 'Porto', 1110);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 12', 'Lisboa', 1120);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 13', 'Braga', 1130);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 14', 'Coimbra', 1140);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 15', 'Faro', 1150);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 16', 'Aveiro', 1160);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 17', 'Guimarães', 1170);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 18', 'Viseu', 1180);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 19', 'Setúbal', 1190);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 20', 'Évora', 1200);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 21', 'Porto', 1210);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 22', 'Lisboa', 1220);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 23', 'Braga', 1230);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 24', 'Coimbra', 1240);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 25', 'Faro', 1250);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 26', 'Aveiro', 1260);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 27', 'Guimarães', 1270);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 28', 'Viseu', 1280);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 29', 'Setúbal', 1290);
INSERT INTO venues (name, city, capacity) VALUES ('Venue 30', 'Évora', 1300);

-- Events
INSERT INTO events (id_venue, name, date, status, description) VALUES (1, 'Event 1', DATE_ADD(NOW(), INTERVAL 1 DAY), 'published', 'Descrição do evento 1');
INSERT INTO events (id_venue, name, date, status, description) VALUES (1, 'Event 2', DATE_ADD(NOW(), INTERVAL 2 DAY), 'published', 'Descrição do evento 2');
INSERT INTO events (id_venue, name, date, status, description) VALUES (2, 'Event 3', DATE_ADD(NOW(), INTERVAL 3 DAY), 'published', 'Descrição do evento 3');
INSERT INTO events (id_venue, name, date, status, description) VALUES (2, 'Event 4', DATE_ADD(NOW(), INTERVAL 4 DAY), 'published', 'Descrição do evento 4');
INSERT INTO events (id_venue, name, date, status, description) VALUES (3, 'Event 5', DATE_ADD(NOW(), INTERVAL 5 DAY), 'published', 'Descrição do evento 5');
INSERT INTO events (id_venue, name, date, status, description) VALUES (3, 'Event 6', DATE_ADD(NOW(), INTERVAL 6 DAY), 'published', 'Descrição do evento 6');
INSERT INTO events (id_venue, name, date, status, description) VALUES (4, 'Event 7', DATE_ADD(NOW(), INTERVAL 7 DAY), 'published', 'Descrição do evento 7');
INSERT INTO events (id_venue, name, date, status, description) VALUES (4, 'Event 8', DATE_ADD(NOW(), INTERVAL 8 DAY), 'published', 'Descrição do evento 8');
INSERT INTO events (id_venue, name, date, status, description) VALUES (5, 'Event 9', DATE_ADD(NOW(), INTERVAL 9 DAY), 'published', 'Descrição do evento 9');
INSERT INTO events (id_venue, name, date, status, description) VALUES (5, 'Event 10', DATE_ADD(NOW(), INTERVAL 10 DAY), 'published', 'Descrição do evento 10');
INSERT INTO events (id_venue, name, date, status, description) VALUES (6, 'Event 11', DATE_ADD(NOW(), INTERVAL 11 DAY), 'published', 'Descrição do evento 11');
INSERT INTO events (id_venue, name, date, status, description) VALUES (6, 'Event 12', DATE_ADD(NOW(), INTERVAL 12 DAY), 'published', 'Descrição do evento 12');
INSERT INTO events (id_venue, name, date, status, description) VALUES (7, 'Event 13', DATE_ADD(NOW(), INTERVAL 13 DAY), 'published', 'Descrição do evento 13');
INSERT INTO events (id_venue, name, date, status, description) VALUES (7, 'Event 14', DATE_ADD(NOW(), INTERVAL 14 DAY), 'published', 'Descrição do evento 14');
INSERT INTO events (id_venue, name, date, status, description) VALUES (8, 'Event 15', DATE_ADD(NOW(), INTERVAL 15 DAY), 'published', 'Descrição do evento 15');
INSERT INTO events (id_venue, name, date, status, description) VALUES (8, 'Event 16', DATE_ADD(NOW(), INTERVAL 16 DAY), 'published', 'Descrição do evento 16');
INSERT INTO events (id_venue, name, date, status, description) VALUES (9, 'Event 17', DATE_ADD(NOW(), INTERVAL 17 DAY), 'published', 'Descrição do evento 17');
INSERT INTO events (id_venue, name, date, status, description) VALUES (9, 'Event 18', DATE_ADD(NOW(), INTERVAL 18 DAY), 'published', 'Descrição do evento 18');
INSERT INTO events (id_venue, name, date, status, description) VALUES (10, 'Event 19', DATE_ADD(NOW(), INTERVAL 19 DAY), 'published', 'Descrição do evento 19');
INSERT INTO events (id_venue, name, date, status, description) VALUES (10, 'Event 20', DATE_ADD(NOW(), INTERVAL 20 DAY), 'published', 'Descrição do evento 20');
INSERT INTO events (id_venue, name, date, status, description) VALUES (11, 'Event 21', DATE_ADD(NOW(), INTERVAL 21 DAY), 'published', 'Descrição do evento 21');
INSERT INTO events (id_venue, name, date, status, description) VALUES (11, 'Event 22', DATE_ADD(NOW(), INTERVAL 22 DAY), 'published', 'Descrição do evento 22');
INSERT INTO events (id_venue, name, date, status, description) VALUES (12, 'Event 23', DATE_ADD(NOW(), INTERVAL 23 DAY), 'published', 'Descrição do evento 23');
INSERT INTO events (id_venue, name, date, status, description) VALUES (12, 'Event 24', DATE_ADD(NOW(), INTERVAL 24 DAY), 'published', 'Descrição do evento 24');
INSERT INTO events (id_venue, name, date, status, description) VALUES (13, 'Event 25', DATE_ADD(NOW(), INTERVAL 25 DAY), 'published', 'Descrição do evento 25');
INSERT INTO events (id_venue, name, date, status, description) VALUES (13, 'Event 26', DATE_ADD(NOW(), INTERVAL 26 DAY), 'published', 'Descrição do evento 26');
INSERT INTO events (id_venue, name, date, status, description) VALUES (14, 'Event 27', DATE_ADD(NOW(), INTERVAL 27 DAY), 'published', 'Descrição do evento 27');
INSERT INTO events (id_venue, name, date, status, description) VALUES (14, 'Event 28', DATE_ADD(NOW(), INTERVAL 28 DAY), 'published', 'Descrição do evento 28');
INSERT INTO events (id_venue, name, date, status, description) VALUES (15, 'Event 29', DATE_ADD(NOW(), INTERVAL 29 DAY), 'published', 'Descrição do evento 29');
INSERT INTO events (id_venue, name, date, status, description) VALUES (15, 'Event 30', DATE_ADD(NOW(), INTERVAL 30 DAY), 'published', 'Descrição do evento 30');
INSERT INTO events (id_venue, name, date, status, description) VALUES (16, 'Event 31', DATE_ADD(NOW(), INTERVAL 31 DAY), 'published', 'Descrição do evento 31');
INSERT INTO events (id_venue, name, date, status, description) VALUES (16, 'Event 32', DATE_ADD(NOW(), INTERVAL 32 DAY), 'published', 'Descrição do evento 32');
INSERT INTO events (id_venue, name, date, status, description) VALUES (17, 'Event 33', DATE_ADD(NOW(), INTERVAL 33 DAY), 'published', 'Descrição do evento 33');
INSERT INTO events (id_venue, name, date, status, description) VALUES (17, 'Event 34', DATE_ADD(NOW(), INTERVAL 34 DAY), 'published', 'Descrição do evento 34');
INSERT INTO events (id_venue, name, date, status, description) VALUES (18, 'Event 35', DATE_ADD(NOW(), INTERVAL 35 DAY), 'published', 'Descrição do evento 35');
INSERT INTO events (id_venue, name, date, status, description) VALUES (18, 'Event 36', DATE_ADD(NOW(), INTERVAL 36 DAY), 'published', 'Descrição do evento 36');
INSERT INTO events (id_venue, name, date, status, description) VALUES (19, 'Event 37', DATE_ADD(NOW(), INTERVAL 37 DAY), 'published', 'Descrição do evento 37');
INSERT INTO events (id_venue, name, date, status, description) VALUES (19, 'Event 38', DATE_ADD(NOW(), INTERVAL 38 DAY), 'published', 'Descrição do evento 38');
INSERT INTO events (id_venue, name, date, status, description) VALUES (20, 'Event 39', DATE_ADD(NOW(), INTERVAL 39 DAY), 'published', 'Descrição do evento 39');
INSERT INTO events (id_venue, name, date, status, description) VALUES (20, 'Event 40', DATE_ADD(NOW(), INTERVAL 40 DAY), 'published', 'Descrição do evento 40');
INSERT INTO events (id_venue, name, date, status, description) VALUES (21, 'Event 41', DATE_ADD(NOW(), INTERVAL 41 DAY), 'published', 'Descrição do evento 41');
INSERT INTO events (id_venue, name, date, status, description) VALUES (21, 'Event 42', DATE_ADD(NOW(), INTERVAL 42 DAY), 'published', 'Descrição do evento 42');
INSERT INTO events (id_venue, name, date, status, description) VALUES (22, 'Event 43', DATE_ADD(NOW(), INTERVAL 43 DAY), 'published', 'Descrição do evento 43');
INSERT INTO events (id_venue, name, date, status, description) VALUES (22, 'Event 44', DATE_ADD(NOW(), INTERVAL 44 DAY), 'published', 'Descrição do evento 44');
INSERT INTO events (id_venue, name, date, status, description) VALUES (23, 'Event 45', DATE_ADD(NOW(), INTERVAL 45 DAY), 'published', 'Descrição do evento 45');
INSERT INTO events (id_venue, name, date, status, description) VALUES (23, 'Event 46', DATE_ADD(NOW(), INTERVAL 46 DAY), 'published', 'Descrição do evento 46');
INSERT INTO events (id_venue, name, date, status, description) VALUES (24, 'Event 47', DATE_ADD(NOW(), INTERVAL 47 DAY), 'published', 'Descrição do evento 47');
INSERT INTO events (id_venue, name, date, status, description) VALUES (24, 'Event 48', DATE_ADD(NOW(), INTERVAL 48 DAY), 'published', 'Descrição do evento 48');
INSERT INTO events (id_venue, name, date, status, description) VALUES (25, 'Event 49', DATE_ADD(NOW(), INTERVAL 49 DAY), 'published', 'Descrição do evento 49');
INSERT INTO events (id_venue, name, date, status, description) VALUES (25, 'Event 50', DATE_ADD(NOW(), INTERVAL 50 DAY), 'published', 'Descrição do evento 50');
INSERT INTO events (id_venue, name, date, status, description) VALUES (26, 'Event 51', DATE_ADD(NOW(), INTERVAL 51 DAY), 'published', 'Descrição do evento 51');
INSERT INTO events (id_venue, name, date, status, description) VALUES (26, 'Event 52', DATE_ADD(NOW(), INTERVAL 52 DAY), 'published', 'Descrição do evento 52');
INSERT INTO events (id_venue, name, date, status, description) VALUES (27, 'Event 53', DATE_ADD(NOW(), INTERVAL 53 DAY), 'published', 'Descrição do evento 53');
INSERT INTO events (id_venue, name, date, status, description) VALUES (27, 'Event 54', DATE_ADD(NOW(), INTERVAL 54 DAY), 'published', 'Descrição do evento 54');
INSERT INTO events (id_venue, name, date, status, description) VALUES (28, 'Event 55', DATE_ADD(NOW(), INTERVAL 55 DAY), 'published', 'Descrição do evento 55');
INSERT INTO events (id_venue, name, date, status, description) VALUES (28, 'Event 56', DATE_ADD(NOW(), INTERVAL 56 DAY), 'published', 'Descrição do evento 56');
INSERT INTO events (id_venue, name, date, status, description) VALUES (29, 'Event 57', DATE_ADD(NOW(), INTERVAL 57 DAY), 'published', 'Descrição do evento 57');
INSERT INTO events (id_venue, name, date, status, description) VALUES (29, 'Event 58', DATE_ADD(NOW(), INTERVAL 58 DAY), 'published', 'Descrição do evento 58');
INSERT INTO events (id_venue, name, date, status, description) VALUES (30, 'Event 59', DATE_ADD(NOW(), INTERVAL 59 DAY), 'published', 'Descrição do evento 59');
INSERT INTO events (id_venue, name, date, status, description) VALUES (30, 'Event 60', DATE_ADD(NOW(), INTERVAL 60 DAY), 'published', 'Descrição do evento 60');

-- Tickets
INSERT INTO tickets (id_event, type, price, status) VALUES (1, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (1, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (1, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (2, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (2, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (2, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (3, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (3, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (3, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (4, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (4, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (4, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (5, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (5, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (5, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (6, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (6, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (6, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (7, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (7, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (7, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (8, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (8, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (8, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (9, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (9, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (9, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (10, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (10, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (10, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (11, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (11, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (11, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (12, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (12, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (12, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (13, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (13, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (13, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (14, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (14, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (14, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (15, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (15, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (15, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (16, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (16, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (16, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (17, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (17, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (17, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (18, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (18, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (18, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (19, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (19, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (19, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (20, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (20, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (20, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (21, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (21, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (21, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (22, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (22, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (22, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (23, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (23, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (23, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (24, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (24, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (24, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (25, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (25, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (25, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (26, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (26, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (26, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (27, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (27, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (27, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (28, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (28, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (28, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (29, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (29, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (29, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (30, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (30, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (30, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (31, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (31, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (31, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (32, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (32, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (32, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (33, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (33, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (33, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (34, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (34, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (34, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (35, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (35, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (35, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (36, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (36, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (36, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (37, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (37, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (37, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (38, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (38, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (38, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (39, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (39, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (39, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (40, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (40, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (40, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (41, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (41, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (41, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (42, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (42, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (42, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (43, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (43, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (43, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (44, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (44, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (44, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (45, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (45, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (45, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (46, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (46, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (46, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (47, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (47, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (47, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (48, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (48, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (48, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (49, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (49, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (49, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (50, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (50, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (50, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (51, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (51, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (51, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (52, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (52, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (52, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (53, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (53, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (53, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (54, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (54, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (54, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (55, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (55, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (55, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (56, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (56, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (56, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (57, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (57, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (57, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (58, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (58, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (58, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (59, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (59, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (59, 'Student', 15.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (60, 'General', 20.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (60, 'VIP', 50.00, 'available');
INSERT INTO tickets (id_event, type, price, status) VALUES (60, 'Student', 15.00, 'available');