version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: p2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: eventosdb
    volumes:
      - dbdata:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: p2-api
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: 12345678
      DB_NAME: eventosdb
      PORT: 3000
      NODE_ENV: production
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  dbdata:
